name: Update HDB Data

on:
  schedule:
    - cron: '0 0 1,15 * *'  # Runs at 00:00 UTC on the 1st and 15th of every month
  workflow_dispatch:        # Allow manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./project
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install
      - run: npm run update-hdb-data
      - name: Commit and push if data changed
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add public/propertyData.json
          git diff --cached --quiet || git commit -m "chore: update HDB data"
          git push 